spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

aws:
  accessKeyId:
  secretKey:
  s3:
    region: SA-EAST-1
    bucket: io.sambatech.challenge


general:
  allowed-content-types: "video/x-matroska"

