spring:
  datasource:
    platform: postgres
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/samba
    username: root
    password:
  jpa:
#    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect


  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB

aws:
  accessKeyId:
  secretKey:
  s3:
    region: SA-EAST-1
    bucket: io.sambatech.challenge


general:
  allowed-content-types: video/x-matroska

bitmovin:
  apiKey: 8dae2340-ed91-41e4-802a-3eee8a836163
  inputId: 56740C7C-F938-4436-B1F6-20243590EECF
  outputId: fae110fd-7c68-45a3-be21-b03031de1e72
  videoCodecConfigId: 64d5e324-caaf-4ce8-8289-a6d8e7edce40
  audioCodecConfigId: eedb299c-929f-4185-85c7-06cee78f1223

